name: ptynn
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python==3.8.*
  - pip
  - numpy
  - tqdm
  - h5py 
  - magma-cuda110
  - cudatoolkit=11.0
  - pytorch=1.7.1
  - tensorboard
  - scikit-image
  - scikit-learn
  - mpi4py
  - requests
  - scikit-image

